# Generated by Django 3.2.9 on 2021-12-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='region',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='healthcentermodels',
            old_name='region',
            new_name='city',
        ),
    ]
